xi4n: ">=0.1.0-unstable"
plugins: 
    - alias: compat
      path: compat
      options: 
    - alias: gauges
      path: gauges
      options: 
        http-port: 8080
connections:
    - talk: insim
      insim:
        over: tcp
        host: 127.0.0.1
        port: 29999
        udpport: 12345
        admin:
        prefix:
      use:
        - compat
        - gauges
      log:
        - level: debug
          type: console
          timestamp: true
        - level: debug
          type: file
          timestamp: true
          filename: error.log
          json: false
